### ISSUE TITLE
UAT Manage Collections

### ISSUE THREAD

**Issue by JasonLazarus7** [fnf-dev/issues#3]
- [x] Export Rows button does not work
- [x] Export Messages button works but only pulls the headings, no data
- [x] View History gives and Unhandled exception error 
- [x] When you assign an agent it doesnt show in events and doesnt save if you refresh the page

**Comment by JasonLazarus7** [comment]
@ryandewberry

**Comment by ryandewberry** [comment]
> * [x]  When you assign an agent it doesnt show in events and doesnt save if you refresh the page

ICM waybills are broken, this works for others

**Comment by JasonLazarus7** [comment]
Thanks Ryan, works perfect for IGI002. The only think i want to try and figure out is how we can balance the data so online matches with Uatonline the total counts
