### ISSUE TITLE
Online.fnf.co.za Fleet Management

### ISSUE THREAD

**Issue by JasonLazarus7** [fnf-dev/issues#4]
- [x]  Scroll feature on Branches cant see the highest performing branches eg MID [https://online.fnf.co.za/Fleet
![Capture](https://user-images.githubusercontent.com/68690452/90113279-6a13e680-dd51-11ea-89b6-596d6e14780e.JPG)
](url)

**Comment by ryandewberry** [comment]
Fixes fnf-dev/issues#4

**Comment by JasonLazarus7** [comment]
Looks Perfect on UAT thanks Ryan
