### ISSUE TITLE
Please add the below accounts to the Problem parcel Portal and rewove from Active returns list in GM

### ISSUE THREAD

**Issue by JasonLazarus7** [fnf-dev/issues#75]
@ryandewberry Ryan please can you add the below accounts to the problem parcel portal.
WIA001; WIA004,WIA005,WIA008

@StephenJ76 Please can you remove these accounts from the Active returns list in GM.

**Comment by StephenJ76** [comment]
Done

 

#close

 

 

Regards

 

Stephen Jacobs

Senior Software Developer

Fast and Furious Distribution (Pty) Ltd

Growthpoint Industrial Estate, Unit 4b, Bell Street, Meadowdale, Edenvale, 1614

 <http://www.fnf.co.za/> www.fnf.co.za | Phone: 010 060 8251 |  <mailto:stephenj@fnf.co.za> stephenj@fnf.co.za 

 



 

This e-mail message and all attachments contain the CONFIDENTIAL AND PROPRIETARY information of F+F and may contain LEGALLY PRIVILEGED information. If you are not the intended recipient, you are hereby notified that any disclosure, distribution, or use of this e-mail, its attachments or any information contained therein is unauthorised and prohibited and may be unlawful. If you have received this in error, please immediately contact the sender and delete this e-mail and any attachments.
